#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
export name="$(yq eval '.metadata.name' /input/object.yaml)"
export size="$(yq eval '.spec.size' /input/object.yaml)"

# Replace defaults with user provided values
cat /tmp/transfer/redis-instance.yaml |  \
  yq eval '.metadata.name = env(name)' | \
  yq eval '.spec.size = env(size)' - \
  > /output/redis-instance.yaml


cat > /output/component.yaml <<EOF
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: rfs-${name}.default.svc.cluster.local:26379
  - name: redisPassword
    value: ""
EOF
